# Usar a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Definir variáveis de ambiente
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD K@micdevelop9812
ENV POSTGRES_DB chfrst

# Copiar scripts de inicialização, se houver
# COPY ./init.sql /docker-entrypoint-initdb.d/
